name: synchroflite
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs) using Sqlite
version: 0.1.6
homepage: https://github.com/JanezStupar/synchroflite
repository: https://github.com/JanezStupar/synchroflite.git
issue_tracker: https://github.com/JanezStupar/synchroflite/issues
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  sqflite_common: 2.5.6
  sqflite_common_ffi: 2.4.0+2
  sqflite_common_ffi_web: 1.1.1
  sql_crdt: 
    git:
      url: https://github.com/VantageSoftwareSolutions/sql_crdt
      ref: eecb3d464f6b119651d0659b13b5fd6c0511a689
  json_annotation: ^4.8.1
  sqlparser: 0.44.3
  source_span: ^1.10.0
  collection: ^1.17.2

dev_dependencies:
  lints: ^4.0.0
  pedantic: ^1.11.1
  test: any
